name: infamous_squircle
description: The infamous squircle with platform aware borders. (pana wants a longer description.)
version: 0.2.0
repository: https://github.com/lukepighetti/infamous_squircle.git

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
